### ISSUE TITLE
Will this work with nrf24l01?

### ISSUE THREAD

**Issue by milapj** [duerrfk/Faros#1]

**Comment by duerrfk** [comment]
No, you need a board with [nRF8001](https://www.nordicsemi.com/eng/Products/Bluetooth-low-energy/nRF8001), such as the [MOD-nRF8001](https://www.olimex.com/Products/Modules/RF/MOD-nRF8001/) (the provided PCB layout is for this board) or [Bluefruit LE](https://www.adafruit.com/product/1697).
